(defun matmul (mat1 mat2)
  (let* ((n (car (array-dimensions mat1)))
         (l1 (cadr (array-dimensions mat1)))
         (l2 (car (array-dimensions mat2)))
         (m (cadr (array-dimensions mat2)))
         (res (make-array (list n m))))
    (if (not (= l1 l2)) (error "Invalid input"))
    (dotimes (i n)
      (dotimes (j m)
        (setf (aref res i j) (loop for k below l1 sum (* (aref mat1 i k) (aref mat2 k j))))))
    res))
